# Tests for Create Variable Plan

##---------------------------------------------------------------
##        1. Test for plan table - generated by default        --
##---------------------------------------------------------------
test_that("Create variable plan - plan table match", {
  options <- jaspTools::analysisOptions("CreateVariablePlan")
  options$aql <- 0.05
  options$rql <- 0.15
  options$prod_risk <- 0.05
  options$cons_risk <- 0.1
  options$pd_lower <- 0
  options$pd_upper <- 0.15
  options$pd_step <- 0.01
  
  options$showSummary <- FALSE
  options$showOCCurve <- FALSE
  options$showAOQCurve <- FALSE
  options$showATICurve <- FALSE
  
  # 1.1 SD known
  options$sd <- TRUE
  results <- jaspTools::runAnalysis("CreateVariablePlan", "test.csv", options)
  varTableKnown <- results[["results"]][["createVarContainer"]][["collection"]][["createVarContainer_plan_table"]][["data"]]
  jaspTools::expect_equal_tables(varTableKnown, list(24, 1.309))

  # 1.2 SD unknown
  options$sd <- FALSE
  results <- jaspTools::runAnalysis("CreateVariablePlan", "test.csv", options)
  varTableUnknown <- results[["results"]][["createVarContainer"]][["collection"]][["createVarContainer_plan_table"]][["data"]]
  jaspTools::expect_equal_tables(varTableUnknown, list(44, 1.311))
})

##---------------------------------------------------------------
##                  2. Test for summary table                  --
##---------------------------------------------------------------
test_that("Create plan - summary table match", {
  options <- jaspTools::analysisOptions("CreateVariablePlan")
  options$aql <- 0.05
  options$rql <- 0.35
  options$prod_risk <- 0.15
  options$cons_risk <- 0.20
  options$pd_lower <- 0.20
  options$pd_upper <- 0.80
  options$pd_step <- 0.05
  options$showSummary <- TRUE
   
  options$showOCCurve <- FALSE
  options$showAOQCurve <- FALSE
  options$showATICurve <- FALSE
  
  # 2.1 SD known
  options$sd <- TRUE
  results <- jaspTools::runAnalysis("CreateVariablePlan", "test.csv", options)
  summaryTableKnown <- results[["results"]][["createVarContainer"]][["collection"]][["createVarContainer_summaryTable"]][["data"]]
  jaspTools::expect_equal_tables(summaryTableKnown, list(
    0.05, 0.85, 0.2, 0.3614, 0.25, 0.2597, 0.3, 0.1829, 0.35, 0.1261, 0.35, 0.1261, 0.4, 0.0848, 0.45, 0.0554, 0.5, 0.035, 0.55,
    0.0212, 0.6, 0.0122, 0.65, 0.0066, 0.7, 0.0033, 0.75, 0.0014, 0.8, 5e-04))
  
  # 2.2 SD unknown
  options$sd <- FALSE
  results <- jaspTools::runAnalysis("CreateVariablePlan", "test.csv", options)
  summaryTableUnknown <- results[["results"]][["createVarContainer"]][["collection"]][["createVarContainer_summaryTable"]][["data"]]
  jaspTools::expect_equal_tables(summaryTableUnknown, list(
    0.05, 0.85, 0.2, 0.4276, 0.25, 0.3283, 0.3, 0.2475, 0.35, 0.1827, 0.35, 0.1827, 0.4, 0.1317, 0.45, 0.0923, 0.5, 0.0625, 0.55,
    0.0407, 0.6, 0.0252, 0.65, 0.0147, 0.7, 0.0079, 0.75, 0.0038, 0.8, 0.0015))
})

##----------------------------------------------------------------
##                     3. Test for OC Curve                     --
##----------------------------------------------------------------
test_that("Create plan - OC Curve match", {
  options <- jaspTools::analysisOptions("CreateVariablePlan")
  options$aql <- 0.001
  options$rql <- 0.20
  options$prod_risk <- 0.02
  options$cons_risk <- 0.45
  options$pd_lower <- 0.02
  options$pd_upper <- 0.99
  options$showOCCurve <- TRUE
  
  options$showSummary <- FALSE
  options$showAOQCurve <- FALSE
  options$showATICurve <- FALSE
  
  # 3.1 SD known
  options$sd <- TRUE
  options$pd_step <- 0.04
  results <- jaspTools::runAnalysis("CreateVariablePlan", "test.csv", options)
  plotName <- results[["results"]][["createVarContainer"]][["collection"]][["createVarContainer_ocCurve"]][["data"]]
  testPlotKnown <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(testPlotKnown, "oc-operating-characteristics-curve-known")
  
  # 3.2 SD unknown
  options$sd <- FALSE
  options$pd_step <- 0.2
  results <- jaspTools::runAnalysis("CreateVariablePlan", "test.csv", options)
  plotName <- results[["results"]][["createVarContainer"]][["collection"]][["createVarContainer_ocCurve"]][["data"]]
  testPlotUnknown <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(testPlotUnknown, "oc-operating-characteristics-curve-unknown")
})

##---------------------------------------------------------------
##                    4. Test for AOQ Curve                    --
##---------------------------------------------------------------
test_that("Create plan - AOQ Curve match", {
  options <- jaspTools::analysisOptions("CreateVariablePlan")
  options$aql <- 0.10
  options$rql <- 0.25
  options$prod_risk <- 0.08
  options$cons_risk <- 0.20
  options$pd_lower <- 0.10
  options$pd_upper <- 0.40
  options$showAOQCurve <- TRUE
  
  options$showSummary <- FALSE
  options$showOCCurve <- FALSE
  options$showATICurve <- FALSE
  
  # 4.1 SD known
  options$sd <- TRUE
  options$pd_step <- 0.01
  results <- jaspTools::runAnalysis("CreateVariablePlan", "test.csv", options)
  plotName <- results[["results"]][["createVarContainer"]][["collection"]][["createVarContainer_aoqCurve"]][["data"]]
  testPlotKnown <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(testPlotKnown, "aoq-curve-known")
  
  # 4.2 SD unknown
  options$sd <- FALSE
  options$pd_step <- 0.2
  results <- jaspTools::runAnalysis("CreateVariablePlan", "test.csv", options)
  plotName <- results[["results"]][["createVarContainer"]][["collection"]][["createVarContainer_aoqCurve"]][["data"]]
  testPlotUnknown <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(testPlotUnknown, "aoq-curve-unknown")
})

##---------------------------------------------------------------
##                    5. Test for ATI Curve                    --
##---------------------------------------------------------------
test_that("Create plan - ATI Curve match", {
  options <- jaspTools::analysisOptions("CreateVariablePlan")
  options$aql <- 0.20
  options$rql <- 0.60
  options$prod_risk <- 0.15
  options$cons_risk <- 0.40
  options$pd_lower <- 0.10
  options$pd_upper <- 0.70
  options$showATICurve <- TRUE
  
  options$showSummary <- FALSE
  options$showOCCurve <- FALSE
  options$showAOQCurve <- FALSE
  
  # 5.1 SD known
  options$sd <- TRUE
  options$pd_step <- 0.05
  results <- jaspTools::runAnalysis("CreateVariablePlan", "test.csv", options)
  plotName <- results[["results"]][["createVarContainer"]][["collection"]][["createVarContainer_atiCurve"]][["data"]]
  testPlotKnown <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(testPlotKnown, "ati-curve-known")
  
  # 5.2 SD unknown
  options$sd <- FALSE
  options$pd_step <- 0.2
  results <- jaspTools::runAnalysis("CreateVariablePlan", "test.csv", options)
  plotName <- results[["results"]][["createVarContainer"]][["collection"]][["createVarContainer_atiCurve"]][["data"]]
  testPlotUnknown <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(testPlotUnknown, "ati-curve-unknown")
})