# Tests for Create Attribute Plan

##--------------------------------------------------------------------
##  1. Test for plan and probability tables - generated by default  --
##--------------------------------------------------------------------
test_that("Create plan - plan and probability tables match", {
  options <- jaspTools::analysisOptions("CreateAttributePlan")
  options$aql <- 0.05
  options$rql <- 0.15
  options$prod_risk <- 0.05
  options$cons_risk <- 0.1
  options$pd_lower <- 0
  options$pd_upper <- 0.15
  options$pd_step <- 0.01
  options$showSummary <- FALSE
  
  # 1.1 Binomial
  options$distribution <- "binom"
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plan_table <- results[["results"]][["createContainer"]][["collection"]][["createContainer_findPlanTable"]][["data"]]
  jaspTools::expect_equal_tables(plan_table, list("Sample size", 77, "Acceptance number", 7))
  prob_table <- results[["results"]][["createContainer"]][["collection"]][["createContainer_findProbTable"]][["data"]]
  jaspTools::expect_equal_tables(prob_table, list("AQL", 0.05, 0.9615, 0.0385, "RQL", 0.15, 0.0925, 0.9075))
  
  # 1.2 Hypergeometric
  options$distribution <- "hypergeom"
  options$lotSize <- 1000
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plan_table <- results[["results"]][["createContainer"]][["collection"]][["createContainer_findPlanTable"]][["data"]]
  jaspTools::expect_equal_tables(plan_table, list("Sample size", 67, "Acceptance number", 6))
  prob_table <- results[["results"]][["createContainer"]][["collection"]][["createContainer_findProbTable"]][["data"]]
  jaspTools::expect_equal_tables(prob_table, list("AQL", 0.05, 0.9564, 0.04364, "RQL", 0.15, 0.0994, 0.9006))
  
  # 1.3 Poisson
  options$distribution <- "poisson"
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plan_table <- results[["results"]][["createContainer"]][["collection"]][["createContainer_findPlanTable"]][["data"]]
  jaspTools::expect_equal_tables(plan_table, list("Sample size", 79, "Acceptance number", 7))
  prob_table <- results[["results"]][["createContainer"]][["collection"]][["createContainer_findProbTable"]][["data"]]
  jaspTools::expect_equal_tables(prob_table, list("AQL", 0.05, 0.9518, 0.0482, "RQL", 0.15, 0.0963, 0.9037))
})

##---------------------------------------------------------------
##                  2. Test for summary table                  --
##---------------------------------------------------------------
test_that("Create plan - summary table match", {
  options <- jaspTools::analysisOptions("CreateAttributePlan")
  options$aql <- 0.02
  options$rql <- 0.20
  options$prod_risk <- 0.09
  options$cons_risk <- 0.15
  options$pd_lower <- 0.05
  options$pd_upper <- 0.35
  options$pd_step <- 0.01
  options$showSummary <- TRUE
  
  # 2.1 Binomial
  options$distribution <- "binom"
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  summaryTable <- results[["results"]][["createContainer"]][["collection"]][["createContainer_summaryTable"]][["data"]]
  jaspTools::expect_equal_tables(summaryTable,
                list(0.02, 0.96, 0.05, 0.811, 0.06, 0.751, 0.07, 0.69, 0.08, 0.63,
                    0.09, 0.571, 0.1, 0.515, 0.11, 0.461, 0.12, 0.412, 0.13, 0.365,
                    0.14, 0.323, 0.15, 0.284, 0.16, 0.249, 0.17, 0.217, 0.18, 0.189,
                    0.19, 0.163, 0.2, 0.141, 0.21, 0.121, 0.22, 0.103, 0.23, 0.088,
                    0.24, 0.075, 0.25, 0.063, 0.26, 0.054, 0.27, 0.045, 0.28, 0.038,
                    0.29, 0.031, 0.3, 0.026, 0.31, 0.022, 0.32, 0.018, 0.33, 0.015,
                    0.34, 0.012, 0.35, 0.01))
  
  # 2.2 Hypergeometric
  options$distribution <- "hypergeom"
  options$lotSize <- 800
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  summaryTable <- results[["results"]][["createContainer"]][["collection"]][["createContainer_summaryTable"]][["data"]]
  jaspTools::expect_equal_tables(summaryTable,
                list(0.02, 0.962, 0.05, 0.812, 0.06, 0.751, 0.07, 0.69, 0.08, 0.629,
                    0.09, 0.57, 0.1, 0.513, 0.11, 0.459, 0.12, 0.409, 0.13, 0.363,
                    0.14, 0.32, 0.15, 0.281, 0.16, 0.246, 0.17, 0.214, 0.18, 0.186,
                    0.19, 0.16, 0.2, 0.138, 0.21, 0.118, 0.22, 0.101, 0.23, 0.086,
                    0.24, 0.073, 0.25, 0.062, 0.26, 0.052, 0.27, 0.043, 0.28, 0.036,
                    0.29, 0.03, 0.3, 0.025, 0.31, 0.021, 0.32, 0.017, 0.33, 0.014,
                    0.34, 0.011, 0.35, 0.009))

  # 2.3 Poisson
  options$distribution <- "poisson"
  options$pd_step <- 0.03
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  summaryTable <- results[["results"]][["createContainer"]][["collection"]][["createContainer_summaryTable"]][["data"]]
  jaspTools::expect_equal_tables(summaryTable,
                list(0.02, 0.954, 0.05, 0.791, 0.08, 0.606, 0.11, 0.442, 0.14, 0.313,
                    0.17, 0.216, 0.2, 0.147, 0.23, 0.098, 0.26, 0.065, 0.29, 0.043,
                    0.32, 0.028, 0.35, 0.018))
})

##----------------------------------------------------------------
##                     3. Test for OC Curve                     --
##----------------------------------------------------------------
test_that("Create plan - OC Curve match", {
  options <- jaspTools::analysisOptions("CreateAttributePlan")
  options$aql <- 0.05
  options$rql <- 0.65
  options$prod_risk <- 0.15
  options$cons_risk <- 0.20
  options$pd_lower <- 0.15
  options$pd_upper <- 0.72
  options$showOCCurve <- TRUE
  
  options$showSummary <- FALSE
  options$showAOQCurve <- FALSE
  options$showATICurve <- FALSE

  # 3.1 Binomial
  options$distribution <- "binom" 
  options$pd_step <- 0.02
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["createContainer"]][["collection"]][["createContainer_ocCurve"]][["data"]]
  testPlotBinom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(testPlotBinom, "oc-operating-characteristics-curve-binom")
  
  # 3.2 Hypergeometric
  options$distribution <- "hypergeom"
  options$lotSize <- 2000
  options$pd_step <- 0.001
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["createContainer"]][["collection"]][["createContainer_ocCurve"]][["data"]]
  testPlotHypergeom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(testPlotHypergeom, "oc-operating-characteristics-curve-hypergeom")

  # 3.3 Poisson
  options$distribution <- "poisson"
  options$pd_step <- 0.05
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["createContainer"]][["collection"]][["createContainer_ocCurve"]][["data"]]
  testPlotPoisson <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(testPlotPoisson, "oc-operating-characteristics-curve-poisson")
})

##---------------------------------------------------------------
##                    4. Test for AOQ Curve                    --
##---------------------------------------------------------------
test_that("Create attribute plan - AOQ Curve match", {
  options <- jaspTools::analysisOptions("CreateAttributePlan")
  options$aql <- 0.20
  options$rql <- 0.40
  options$prod_risk <- 0.25
  options$cons_risk <- 0.45
  options$pd_lower <- 0.1
  options$pd_upper <- 0.9
  options$showAOQCurve <- TRUE
  
  options$showSummary <- FALSE
  options$showOCCurve <- FALSE
  options$showATICurve <- FALSE
  
  # 4.1 Binomial
  options$distribution <- "binom"
  options$lotSize <- 1000
  options$pd_step <- 0.1
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["createContainer"]][["collection"]][["createContainer_aoqCurve"]][["data"]]
  aoqPlotBinom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(aoqPlotBinom, "aoq-curve--binom")
  
  # 4.2 Hypergeometric
  options$distribution <- "hypergeom"
  options$lotSize <- 500
  options$sampleSize <- 100
  options$pd_step <- 0.05
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["createContainer"]][["collection"]][["createContainer_aoqCurve"]][["data"]]
  aoqPlotHypergeom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(aoqPlotHypergeom, "aoq-curve--hypergeom")

  # 4.3 Poisson
  options$distribution <- "poisson"
  options$lotSize <- 400
  options$sampleSize <- 50
  options$pd_step <- 0.01
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["createContainer"]][["collection"]][["createContainer_aoqCurve"]][["data"]]
  aoqPlotPoisson <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(aoqPlotPoisson, "aoq-curve--poisson")
})

##---------------------------------------------------------------
##                    5. Test for ATI Curve                    --
##---------------------------------------------------------------
test_that("Create attribute plan - ATI Curve match", {
  options <- jaspTools::analysisOptions("CreateAttributePlan")
  options$aql <- 0.08
  options$rql <- 0.65
  options$prod_risk <- 0.18
  options$cons_risk <- 0.38
  options$pd_lower <- 0.04
  options$pd_upper <- 0.78
  
  options$showATICurve <- TRUE
  
  options$showSummary <- FALSE
  options$showOCCurve <- FALSE
  options$showAOQCurve <- FALSE
  
  # 5.1 Binomial
  options$distribution <- "binom"
  options$lotSize <- 750
  options$pd_step <- 0.2
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["createContainer"]][["collection"]][["createContainer_atiCurve"]][["data"]]
  atiPlotBinom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotBinom, "ati-curve--binom")
  
  # 5.2 Hypergeometric
  options$distribution <- "hypergeom"
  options$lotSize <- 600
  options$pd_step <- 0.1
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["createContainer"]][["collection"]][["createContainer_atiCurve"]][["data"]]
  atiPlotHypergeom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotHypergeom, "ati-curve--hypergeom")

  # 5.3 Poisson
  options$distribution <- "poisson"
  options$lotSize <- 300
  options$pd_step <- 0.05
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["createContainer"]][["collection"]][["createContainer_atiCurve"]][["data"]]
  atiPlotPoisson <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotPoisson, "ati-curve--poisson")
})