# Tests for Analyze Variable Plan

##---------------------------------------------------------------
##        1. Test for plan table - generated by default        --
##---------------------------------------------------------------
test_that("Analyze variable plan - plan table match", {
  options <- jaspTools::analysisOptions("AnalyzeVariablePlan")
  options$sampleSize <- 24
  options$kValue <- 1.309
  options$pd_lower <- 0
  options$pd_upper <- 1
  options$pd_step <- 0.05
  
  options$assessPlan <- FALSE
  options$showSummary <- FALSE
  options$showOCCurve <- FALSE
  options$showAOQCurve <- FALSE
  options$showATICurve <- FALSE
  
  # 1.1 SD known. Default values for n and k.
  options$sd <- TRUE
  results <- jaspTools::runAnalysis("AnalyzeVariablePlan", "test.csv", options)
  varTitleKnown <- results[["results"]][["analyzeVarContainer"]][["collection"]][["analyzeVarContainer_plan_table"]][["title"]]
  expect_that(varTitleKnown, equals("Variable Sampling Plan (Standard deviation assumed to be <b>known</b>)"))
  varTableKnown <- results[["results"]][["analyzeVarContainer"]][["collection"]][["analyzeVarContainer_plan_table"]][["data"]]
  jaspTools::expect_equal_tables(varTableKnown, list(24, 1.309))
  
  # 1.2 SD unknown
  options$sd <- FALSE
  options$sampleSize <- 224
  options$kValue <- 23.45
  results <- jaspTools::runAnalysis("AnalyzeVariablePlan", "test.csv", options)
  varTitleUnknown <- results[["results"]][["analyzeVarContainer"]][["collection"]][["analyzeVarContainer_plan_table"]][["title"]]
  expect_that(varTitleUnknown, equals("Variable Sampling Plan (Standard deviation assumed to be <b>unknown</b>)"))
  varTableUnknown <- results[["results"]][["analyzeVarContainer"]][["collection"]][["analyzeVarContainer_plan_table"]][["data"]]
  jaspTools::expect_equal_tables(varTableUnknown, list(224, 23.45))
})

##---------------------------------------------------------------
##                  2. Test for summary table                  --
##---------------------------------------------------------------
test_that("Analyze plan - summary table match", {
  options <- jaspTools::analysisOptions("AnalyzeVariablePlan")
  options$sampleSize <- 3
  options$kValue <- 1.046
  options$pd_lower <- 0.20
  options$pd_upper <- 0.80
  options$pd_step <- 0.05
  options$showSummary <- TRUE
  
  options$assessPlan <- FALSE
  options$showOCCurve <- FALSE
  options$showAOQCurve <- FALSE
  options$showATICurve <- FALSE
  
  # 2.1 SD known
  options$sd <- TRUE
  results <- jaspTools::runAnalysis("AnalyzeVariablePlan", "test.csv", options)
  summaryTableKnown <- results[["results"]][["analyzeVarContainer"]][["collection"]][["analyzeVarContainer_summaryTable"]][["data"]]
  jaspTools::expect_equal_tables(summaryTableKnown, list(
    0.2, 0.3617, 0.25, 0.26, 0.3, 0.1831, 0.35, 0.1262, 0.4, 0.0849, 0.45, 0.0555, 0.5, 0.035, 0.55, 0.0212, 0.6, 0.0122, 0.65, 0.0066,
    0.7, 0.0033, 0.75, 0.0014, 0.8, 5e-04))
  
  # 2.2 SD unknown
  options$sd <- FALSE
  results <- jaspTools::runAnalysis("AnalyzeVariablePlan", "test.csv", options)
  summaryTableUnknown <- results[["results"]][["analyzeVarContainer"]][["collection"]][["analyzeVarContainer_summaryTable"]][["data"]]
  jaspTools::expect_equal_tables(summaryTableUnknown, list(
    0.2, 0.4664, 0.25, 0.3786, 0.3, 0.3036, 0.35, 0.2401, 0.4, 0.1867, 0.45, 0.1423, 0.5, 0.1059, 0.55, 0.0764, 0.6, 0.0532, 0.65, 0.0353,
    0.7, 0.0221, 0.75, 0.0127, 0.8, 0.0064))
})

##---------------------------------------------------------------
##                   3. Test for assess plan                   --
##---------------------------------------------------------------
test_that("Analyze plan - assess table match", {
  options <- jaspTools::analysisOptions("AnalyzeVariablePlan")
  options$lotSize <- 1000
  options$sampleSize <- 6
  options$kValue <- 0.789
  options$pd_lower <- 0.02
  options$pd_upper <- 0.99
  options$pd_step <- 0.001
  options$assessPlan <- TRUE
  options$aql <- 0.001
  options$rql <- 0.09
  options$prod_risk <- 0.15
  options$cons_risk <- 0.23
  
  options$showSummary <- FALSE
  options$showOCCurve <- FALSE
  options$showAOQCurve <- FALSE
  options$showATICurve <- FALSE
  
  # 3.1 SD known
  options$sd <- TRUE
  results <- jaspTools::runAnalysis("AnalyzeVariablePlan", "test.csv", options)
  assessTableTitle <- results[["results"]][["analyzeVarContainer"]][["collection"]][["analyzeVarContainer_riskTable"]][["title"]]
  expect_that(assessTableTitle, equals("Current plan <b>CAN NOT</b> meet the specified risk point(s)."))
  assessTableKnown <- results[["results"]][["analyzeVarContainer"]][["collection"]][["analyzeVarContainer_riskTable"]][["data"]]
  jaspTools::expect_equal_tables(assessTableKnown, list("AQL", 0.001, 0.85, 1, "RQL", 0.09, 0.23, 0.9117))
  assessExplanation <- results[["results"]][["analyzeVarContainer"]][["collection"]][["analyzeVarContainer_explanation"]][["rawtext"]]
  expect_that(assessExplanation, equals("Probability of acceptance (0.912) at RQL (0.090) is <b>higher</b> than the required probability of acceptance (0.230) at RQL."))

  
  # 3.2 SD unknown
  options$sd <- FALSE
  options$prod_risk <- 0.05
  options$cons_risk <- 0.915
  results <- jaspTools::runAnalysis("AnalyzeVariablePlan", "test.csv", options)
  assessTableTitle <- results[["results"]][["analyzeVarContainer"]][["collection"]][["analyzeVarContainer_riskTable"]][["title"]]
  expect_that(assessTableTitle, equals("Current plan <b>CAN </b> meet the specified risk point(s)."))
  assessTableKnown <- results[["results"]][["analyzeVarContainer"]][["collection"]][["analyzeVarContainer_riskTable"]][["data"]]
  jaspTools::expect_equal_tables(assessTableKnown, list("AQL", 0.001, 0.95, 1, "RQL", 0.09, 0.915, 0.8921))
  assessExplanation <- results[["results"]][["analyzeVarContainer"]][["collection"]][["analyzeVarContainer_explanation"]][["rawtext"]]
  expect_that(assessExplanation, equals(NULL))
})

##----------------------------------------------------------------
##                     4. Test for OC Curve                     --
##----------------------------------------------------------------
test_that("Analyze plan - OC Curve match", {
  options <- jaspTools::analysisOptions("AnalyzeVariablePlan")
  options$lotSize <- 500
  options$sampleSize <- 9
  options$kValue <- 0.56
  options$pd_lower <- 0.01
  options$pd_upper <- 0.18
  options$showOCCurve <- TRUE
  
  options$assessPlan <- FALSE
  options$showSummary <- FALSE
  options$showAOQCurve <- FALSE
  options$showATICurve <- FALSE
  
  # 4.1 SD known
  options$sd <- TRUE
  options$pd_step <- 0.04
  results <- jaspTools::runAnalysis("AnalyzeVariablePlan", "test.csv", options)
  plotName <- results[["results"]][["analyzeVarContainer"]][["collection"]][["analyzeVarContainer_ocCurve"]][["data"]]
  testPlotKnown <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(testPlotKnown, "oc-operating-characteristics-curve-known")
  
  # 4.2 SD unknown
  options$sd <- FALSE
  options$pd_step <- 0.02
  results <- jaspTools::runAnalysis("AnalyzeVariablePlan", "test.csv", options)
  plotName <- results[["results"]][["analyzeVarContainer"]][["collection"]][["analyzeVarContainer_ocCurve"]][["data"]]
  testPlotUnknown <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(testPlotUnknown, "oc-operating-characteristics-curve-unknown")
})

##---------------------------------------------------------------
##                    5. Test for AOQ Curve                    --
##---------------------------------------------------------------
test_that("Analyze plan - AOQ Curve match", {
  skip_on_os(c("mac", "linux"))
  options <- jaspTools::analysisOptions("AnalyzeVariablePlan")
  options$lotSize <- 200
  options$sampleSize <- 4
  options$kValue <- 0.8
  options$pd_lower <- 0.01
  options$pd_upper <- 0.40
  options$showAOQCurve <- TRUE
  
  options$assessPlan <- FALSE
  options$showSummary <- FALSE
  options$showOCCurve <- FALSE
  options$showATICurve <- FALSE
  
  # 5.1 SD known
  options$sd <- TRUE
  options$pd_step <- 0.01
  results <- jaspTools::runAnalysis("AnalyzeVariablePlan", "test.csv", options)
  plotName <- results[["results"]][["analyzeVarContainer"]][["collection"]][["analyzeVarContainer_aoqCurve"]][["data"]]
  testPlotKnown <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(testPlotKnown, "aoq-curve-known")
  
  # 5.2 SD unknown
  options$sd <- FALSE
  options$pd_step <- 0.05
  results <- jaspTools::runAnalysis("AnalyzeVariablePlan", "test.csv", options)
  plotName <- results[["results"]][["analyzeVarContainer"]][["collection"]][["analyzeVarContainer_aoqCurve"]][["data"]]
  testPlotUnknown <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(testPlotUnknown, "aoq-curve-unknown")
})

##---------------------------------------------------------------
##                    6. Test for ATI Curve                    --
##---------------------------------------------------------------
test_that("Analyze plan - ATI Curve match", {
  options <- jaspTools::analysisOptions("AnalyzeVariablePlan")
  options$lotSize <- 300
  options$sampleSize <- 11
  options$kValue <- 1.1
  options$pd_lower <- 0.04
  options$pd_upper <- 0.87
  options$showATICurve <- TRUE
  
  options$assessPlan <- FALSE
  options$showSummary <- FALSE
  options$showOCCurve <- FALSE
  options$showAOQCurve <- FALSE
  
  # 6.1 SD known
  options$sd <- TRUE
  options$pd_step <- 0.04
  results <- jaspTools::runAnalysis("AnalyzeVariablePlan", "test.csv", options)
  plotName <- results[["results"]][["analyzeVarContainer"]][["collection"]][["analyzeVarContainer_atiCurve"]][["data"]]
  testPlotKnown <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(testPlotKnown, "ati-curve-known")
  
  # 6.2 SD unknown
  options$sd <- FALSE
  options$pd_step <- 0.03
  results <- jaspTools::runAnalysis("AnalyzeVariablePlan", "test.csv", options)
  plotName <- results[["results"]][["analyzeVarContainer"]][["collection"]][["analyzeVarContainer_atiCurve"]][["data"]]
  testPlotUnknown <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(testPlotUnknown, "ati-curve-unknown")
})