# Tests for Analyze Attribute Plan

#################################################################
##                   1. Single sampling plan                   ##
#################################################################

##----------------------------------------------------------------
##        1.1 Test for plan table - generated by default        --
##----------------------------------------------------------------
test_that("Analyze attribute plan single - plan table match", {
  options <- jaspTools::analysisOptions("AnalyzeAttributePlan")
  options$lotSizeSingle <- 500
  options$sampleSizeSingle <- 250
  options$acceptNumberSingle <- 10
  options$rejectNumberSingle <- 11
  options$pd_lowerSingle <- 0
  options$pd_upperSingle <- 1
  options$pd_stepSingle <- 0.05
  options$distributionSingle <- "binom"
  
  options$assessPlanSingle <- FALSE
  options$showSummarySingle <- FALSE
  options$showOCCurveSingle <- FALSE
  options$showAOQCurveSingle <- FALSE
  options$showATICurveSingle <- FALSE
  options$showASNCurveSingle <- FALSE
  
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  plan_table <- results[["results"]][["singleContainer"]][["collection"]][["singleContainer_plan_table"]][["data"]]
  jaspTools::expect_equal_tables(plan_table, list("Sample size", 250, "Acceptance number", 10))
})
#################################################################################################################

##---------------------------------------------------------------
##                  1.2 Test for assess table                  --
##---------------------------------------------------------------
test_that("Analyze attribute plan single - assess table match", {
  options <- jaspTools::analysisOptions("AnalyzeAttributePlan")
  options$lotSizeSingle <- 100
  options$sampleSizeSingle <- 50
  options$acceptNumberSingle <- 2
  options$rejectNumberSingle <- 3
  options$pd_lowerSingle <- 0
  options$pd_upperSingle <- 1
  options$pd_stepSingle <- 0.5
  options$distributionSingle <- "hypergeom"
  
  options$assessPlanSingle <- TRUE
  options$aqlSingle <- 0.05
  options$rqlSingle <- 0.15
  options$prod_riskSingle <- 0.05
  options$cons_riskSingle <- 0.1
  options$showSummarySingle <- FALSE
  options$showOCCurveSingle <- FALSE
  options$showAOQCurveSingle <- FALSE
  options$showATICurveSingle <- FALSE
  options$showASNCurveSingle <- FALSE
  
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  assessTableTitle <- results[["results"]][["singleContainer"]][["collection"]][["singleContainer_riskTable"]][["title"]]
  expect_that(assessTableTitle, equals("Current plan <b>CAN NOT</b> meet the specified risk point(s)."))
  assessTable <- results[["results"]][["singleContainer"]][["collection"]][["singleContainer_riskTable"]][["data"]]
  jaspTools::expect_equal_tables(assessTable, list("AQL", 0.05, 0.95, 0.5, "RQL", 0.15, 0.1, 0.0019))
  assessExplanation <- results[["results"]][["singleContainer"]][["collection"]][["singleContainer_explanation"]][["rawtext"]]
  expect_that(assessExplanation, equals("Probability of acceptance (0.500) at AQL (0.050) is <b>lower</b> than the required probability of acceptance (0.950) at AQL."))
})

##----------------------------------------------------------------
##                    1.3 Test for AOQ Curve                    --
##----------------------------------------------------------------
test_that("Analyze attribute plan single - AOQ Curve match", {
  options <- jaspTools::analysisOptions("AnalyzeAttributePlan")
  options$lotSizeSingle <- 2000
  options$sampleSizeSingle <- 200
  options$acceptNumberSingle <- 10
  options$rejectNumberSingle <- 11
  options$pd_lowerSingle <- 0.05
  options$pd_upperSingle <- 0.25
  options$pd_stepSingle <- 0.01
  
  options$showAOQCurveSingle <- TRUE
  options$assessPlanSingle <- FALSE
  options$showSummarySingle <- FALSE
  options$showOCCurveSingle <- FALSE
  options$showATICurveSingle <- FALSE
  options$showASNCurveSingle <- FALSE
  
  # 1.3.1 Binomial
  options$distributionSingle <- "binom"
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["singleContainer"]][["collection"]][["singleContainer_aoqCurve"]][["data"]]
  aoqPlotBinom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(aoqPlotBinom, "aoq-curve-single-binom")
  
  # 1.3.2 Hypergeometric
  options$distributionSingle <- "hypergeom"
  options$lotSize <- 1000
  options$sampleSizeSingle <- 100
  options$pd_step <- 0.05
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["singleContainer"]][["collection"]][["singleContainer_aoqCurve"]][["data"]]
  aoqPlotHypergeom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(aoqPlotHypergeom, "aoq-curve-single-hypergeom")

  # 1.3.3 Poisson
  options$distributionSingle <- "poisson"
  options$lotSize <-  500 
  options$sampleSizeSingle <- 50
  options$pd_step <- 0.1
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["singleContainer"]][["collection"]][["singleContainer_aoqCurve"]][["data"]]
  aoqPlotPoisson <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(aoqPlotPoisson, "aoq-curve-single-poisson")
})

##----------------------------------------------------------------
##                    1.4 Test for ATI Curve                    --
##----------------------------------------------------------------
test_that("Analyze attribute plan single - ATI Curve match", {
  options <- jaspTools::analysisOptions("AnalyzeAttributePlan")
  options$lotSizeSingle <- 400
  options$sampleSizeSingle <- 80
  options$acceptNumberSingle <- 4
  options$rejectNumberSingle <- 5
  options$pd_lowerSingle <- 0.10
  options$pd_upperSingle <- 0.35
  options$pd_stepSingle <- 0.02
  
  options$showATICurveSingle <- TRUE
  options$assessPlanSingle <- FALSE
  options$showSummarySingle <- FALSE
  options$showOCCurveSingle <- FALSE
  options$showAOQCurveSingle <- FALSE
  options$showASNCurveSingle <- FALSE
  
  # 1.4.1 Binomial
  options$distributionSingle <- "binom"
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["singleContainer"]][["collection"]][["singleContainer_atiCurve"]][["data"]]
  atiPlotBinom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotBinom, "ati-curve-single-binom")
  
  # 1.4.2 Hypergeometric
  options$distributionSingle <- "hypergeom"
  options$lotSize <- 600
  options$sampleSizeSingle <- 70
  options$pd_step <- 0.03
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["singleContainer"]][["collection"]][["singleContainer_atiCurve"]][["data"]]
  atiPlotHypergeom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotHypergeom, "ati-curve-single-hypergeom")

  # 1.4.3 Poisson
  options$distributionSingle <- "poisson"
  options$lotSize <- 100
  options$sampleSizeSingle <- 20
  options$pd_step <- 0.005
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["singleContainer"]][["collection"]][["singleContainer_atiCurve"]][["data"]]
  atiPlotPoisson <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotPoisson, "ati-curve-single-poisson")
})

#################################################################
##                  2. Multiple sampling plan                  ##
#################################################################

##----------------------------------------------------------------
##        2.1 Test for plan table - generated by default        --
##----------------------------------------------------------------
test_that("Analyze attribute plan multiple - plan table match", {
  options <- jaspTools::analysisOptions("AnalyzeAttributePlan")
  options$lotSizeMult <- 1000
  options$numberOfStages <- 2
  n <- c(30,30)
  c <- c(0,3)
  r <- c(2,4)
  stages <- list()
  for (i in 1:options$numberOfStages) {
    stages[[i]] <- list(acceptNumberMult=c[i], rejectNumberMult=r[i], sampleSizeMult=n[i], value=i)
  }
  options$stages <- stages
  options$pd_lowerMult <- 0
  options$pd_upperMult <- 1
  options$pd_stepMult <- 0.05
  options$distributionMult <- "binom"
  
  options$sampleSizeSingle <- 0 # To avoid single plan calculations
  options$assessPlanMult <- FALSE
  options$showSummaryMult <- FALSE
  options$showOCCurveMult <- FALSE
  options$showAOQCurveMult <- FALSE
  options$showATICurveMult <- FALSE
  options$showASNCurveMult <- FALSE
  
  # 2.1.1 Default table with 2 stages:
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  plan_table <- results[["results"]][["multContainer"]][["collection"]][["multContainer_plan_table"]][["data"]]
  jaspTools::expect_equal_tables(plan_table, list(1, 30, 30, 0, 2, 2, 30, 60, 3, 4))
  
  # 2.1.2 Table with 6 stages:
  options$numberOfStages <- 6
  n <- c(46,46,46,46,46,46)
  c <- c(0,1,2,3,4,6)
  r <- c(3,3,4,5,6,7)
  for (i in 1:options$numberOfStages) {
    stages[[i]] <- list(acceptNumberMult=c[i], rejectNumberMult=r[i], sampleSizeMult=n[i], value=i)
  }
  options$stages <- stages
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  plan_table <- results[["results"]][["multContainer"]][["collection"]][["multContainer_plan_table"]][["data"]]
  jaspTools::expect_equal_tables(plan_table, list(1, 46, 46, 0, 3, 2, 46, 92, 1, 3, 3, 46, 138, 2, 4, 4, 46, 184, 
                                              3, 5, 5, 46, 230, 4, 6, 6, 46, 276, 6, 7))
})

##---------------------------------------------------------------
##                  2.2 Test for assess table                  --
##---------------------------------------------------------------
test_that("Analyze attribute plan Mult - assess table match", {
  options <- jaspTools::analysisOptions("AnalyzeAttributePlan")
  options$lotSizeMult <- 800
  options$numberOfStages <- 6
  n <- c(46,46,46,46,46,46)
  c <- c(0,1,2,3,4,6)
  r <- c(3,3,4,5,6,7)
  stages <- list()
  for (i in 1:options$numberOfStages) {
    stages[[i]] <- list(acceptNumberMult=c[i], rejectNumberMult=r[i], sampleSizeMult=n[i], value=i)
  }
  options$stages <- stages
  options$pd_lowerMult <- 0
  options$pd_upperMult <- 0.75
  options$pd_stepMult <- 0.02
  options$distributionMult <- "binom"
  
  options$sampleSizeSingle <- 0 # To avoid single plan calculations
  options$showSummaryMult <- FALSE
  options$showOCCurveMult <- FALSE
  options$showAOQCurveMult <- FALSE
  options$showATICurveMult <- FALSE
  options$showASNCurveMult <- FALSE
  
  options$assessPlanMult <- TRUE
  options$aqlMult <- 0.05
  options$rqlMult <- 0.15
  options$prod_riskMult <- 0.05
  options$cons_riskMult <- 0.1
  
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  assessTableTitle <- results[["results"]][["multContainer"]][["collection"]][["multContainer_riskTable"]][["title"]]
  expect_that(assessTableTitle, equals("Current plan <b>CAN NOT</b> meet the specified risk point(s)."))
  assessTable <- results[["results"]][["multContainer"]][["collection"]][["multContainer_riskTable"]][["data"]]
  jaspTools::expect_equal_tables(assessTable, list("AQL", 0.05, 0.95, 0.1258, "RQL", 0.15, 0.1, 6e-04))
  assessExplanation <- results[["results"]][["multContainer"]][["collection"]][["multContainer_explanation"]][["rawtext"]]
  expect_that(assessExplanation, equals("Probability of acceptance (0.126) at AQL (0.050) is <b>lower</b> than the required probability of acceptance (0.950) at AQL."))
})

##----------------------------------------------------------------
##                    2.3 Test for AOQ Curve                    --
##----------------------------------------------------------------
test_that("Analyze attribute plan Mult - AOQ Curve match", {
  options <- jaspTools::analysisOptions("AnalyzeAttributePlan")
  options$lotSizeMult <- 400
  options$numberOfStages <- 3
  n <- c(35,45,55)
  c <- c(0,3,6)
  r <- c(2,5,7)
  stages <- list()
  for (i in 1:options$numberOfStages) {
    stages[[i]] <- list(acceptNumberMult=c[i], rejectNumberMult=r[i], sampleSizeMult=n[i], value=i)
  }
  options$stages <- stages
  options$pd_lowerMult <- 0.08
  options$pd_upperMult <- 0.95
  options$pd_stepMult <- 0.04
  
  options$showAOQCurveMult <- TRUE

  options$sampleSizeSingle <- 0 # To avoid single plan calculations
  options$assessPlanMult <- FALSE
  options$showSummaryMult <- FALSE
  options$showOCCurveMult <- FALSE
  options$showATICurveMult <- FALSE
  options$showASNCurveMult <- FALSE
  
  # 2.3.1 Binomial
  options$distributionMult <- "binom"
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["multContainer"]][["collection"]][["multContainer_aoqCurve"]][["data"]]
  aoqPlotBinom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(aoqPlotBinom, "aoq-curve-Mult-binom")
  
  # 2.3.2 Hypergeometric
  options$distributionMult <- "hypergeom"
  options$lotSizeMult <- 600
  options$pd_stepMult <- 0.03
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["multContainer"]][["collection"]][["multContainer_aoqCurve"]][["data"]]
  aoqPlotHypergeom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(aoqPlotHypergeom, "aoq-curve-Mult-hypergeom")

  # 2.3.3 Poisson
  options$distributionMult <- "poisson"
  options$lotSizeMult <- 800
  options$pd_stepMult <- 0.1
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["multContainer"]][["collection"]][["multContainer_aoqCurve"]][["data"]]
  aoqPlotPoisson <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(aoqPlotPoisson, "aoq-curve-Mult-poisson")
})

##----------------------------------------------------------------
##                    2.4 Test for ATI Curve                    --
##----------------------------------------------------------------
test_that("Analyze attribute plan Mult - ATI Curve match", {
  options <- jaspTools::analysisOptions("AnalyzeAttributePlan")
  options$lotSizeMult <- 400
  options$numberOfStages <- 4
  n <- c(20,15,15,25)
  c <- c(0,3,6,9)
  r <- c(2,5,8,10)
  stages <- list()
  for (i in 1:options$numberOfStages) {
    stages[[i]] <- list(acceptNumberMult=c[i], rejectNumberMult=r[i], sampleSizeMult=n[i], value=i)
  }
  options$stages <- stages
  options$pd_lowerMult <- 0.10
  options$pd_upperMult <- 0.22
  options$pd_stepMult <- 0.002
  
  options$showATICurveMult <- TRUE

  options$sampleSizeSingle <- 0 # To avoid single plan calculations
  options$assessPlanMult <- FALSE
  options$showSummaryMult <- FALSE
  options$showOCCurveMult <- FALSE
  options$showAOQCurveMult <- FALSE
  options$showASNCurveMult <- FALSE
  
  # 2.4.1 Binomial
  options$distributionMult <- "binom"
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["multContainer"]][["collection"]][["multContainer_atiCurve"]][["data"]]
  atiPlotBinom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotBinom, "ati-curve-Mult-binom")
  
  # 2.4.2 Hypergeometric
  options$distributionMult <- "hypergeom"
  options$lotSizeMult <- 300
  options$pd_stepMult <- 0.01
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["multContainer"]][["collection"]][["multContainer_atiCurve"]][["data"]]
  atiPlotHypergeom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotHypergeom, "ati-curve-Mult-hypergeom")

  # 2.4.3 Poisson
  options$distributionMult <- "poisson"
  options$lotSizeMult <- 200
  options$pd_stepMult <- 0.02
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["multContainer"]][["collection"]][["multContainer_atiCurve"]][["data"]]
  atiPlotPoisson <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotPoisson, "ati-curve-Mult-poisson")
})

##----------------------------------------------------------------
##                    2.5 Test for ASN Curve                    --
##----------------------------------------------------------------
test_that("Analyze attribute plan Mult - ASN Curve match", {
  options <- jaspTools::analysisOptions("AnalyzeAttributePlan")
  options$lotSizeMult <- 500
  options$numberOfStages <- 7
  n <- c(10,12,12,15,15,20,50)
  c <- c(0,3,6,9,12,15,18)
  r <- c(2,5,8,11,14,17,19)
  stages <- list()
  for (i in 1:options$numberOfStages) {
    stages[[i]] <- list(acceptNumberMult=c[i], rejectNumberMult=r[i], sampleSizeMult=n[i], value=i)
  }
  options$stages <- stages
  options$pd_lowerMult <- 0.005
  options$pd_upperMult <- 0.355
  options$pd_stepMult <- 0.01
  
  options$showASNCurveMult <- TRUE
  
  options$sampleSizeSingle <- 0 # To avoid single plan calculations
  options$assessPlanMult <- FALSE
  options$showSummaryMult <- FALSE
  options$showOCCurveMult <- FALSE
  options$showAOQCurveMult <- FALSE
  options$showATICurveMult <- FALSE
  
  # 2.5.1 Binomial
  options$distributionMult <- "binom"
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["multContainer"]][["collection"]][["multContainer_asnCurve"]][["data"]]
  asnPlotBinom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(asnPlotBinom, "asn-curve-Mult-binom")
  
  # 2.5.2 Hypergeometric
  options$distributionMult <- "hypergeom"
  options$lotSizeMult <- 600
  options$pd_stepMult <- 0.05
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["multContainer"]][["collection"]][["multContainer_asnCurve"]][["data"]]
  asnPlotHypergeom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(asnPlotHypergeom, "asn-curve-Mult-hypergeom")

  # 2.5.3 Poisson
  options$distributionMult <- "poisson"
  options$lotSizeMult <- 2000
  options$pd_stepMult <- 0.06
  results <- jaspTools::runAnalysis("AnalyzeAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["multContainer"]][["collection"]][["multContainer_asnCurve"]][["data"]]
  asnPlotPoisson <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(asnPlotPoisson, "asn-curve-Mult-poisson")
})