# Tests for Create Attribute Plan

##--------------------------------------------------------------------
##  1. Test for plan and probability tables - generated by default  --
##--------------------------------------------------------------------
test_that("Create plan - plan and probability tables match", {
  options <- jaspTools::analysisOptions("CreateAttributePlan")
  options$aql <- 0.05
  options$rql <- 0.15
  options$prod_risk <- 0.05
  options$cons_risk <- 0.1
  options$pd_lower <- 0
  options$pd_upper <- 0.15
  options$pd_step <- 0.01
  options$showSummary <- FALSE
  
  # 1.1 Binomial
  options$distribution <- "binom"
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plan_table <- results[["results"]][["createContainer"]][["collection"]][["createContainer_findPlanTable"]][["data"]]
  jaspTools::expect_equal_tables(plan_table, list("Sample size", 77, "Acceptance number", 7))
  prob_table <- results[["results"]][["createContainer"]][["collection"]][["createContainer_findProbTable"]][["data"]]
  jaspTools::expect_equal_tables(prob_table, list("AQL", 0.05, 0.9615, 0.0385, "RQL", 0.15, 0.0925, 0.9075))
  
  # 1.2 Hypergeometric
  options$distribution <- "hypergeom"
  options$lotSize <- 1000
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plan_table <- results[["results"]][["createContainer"]][["collection"]][["createContainer_findPlanTable"]][["data"]]
  jaspTools::expect_equal_tables(plan_table, list("Sample size", 67, "Acceptance number", 6))
  prob_table <- results[["results"]][["createContainer"]][["collection"]][["createContainer_findProbTable"]][["data"]]
  jaspTools::expect_equal_tables(prob_table, list("AQL", 0.05, 0.9564, 0.04364, "RQL", 0.15, 0.0994, 0.9006))
  
  # 1.3 Poisson
  options$distribution <- "poisson"
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plan_table <- results[["results"]][["createContainer"]][["collection"]][["createContainer_findPlanTable"]][["data"]]
  jaspTools::expect_equal_tables(plan_table, list("Sample size", 79, "Acceptance number", 7))
  prob_table <- results[["results"]][["createContainer"]][["collection"]][["createContainer_findProbTable"]][["data"]]
  jaspTools::expect_equal_tables(prob_table, list("AQL", 0.05, 0.9518, 0.0482, "RQL", 0.15, 0.0963, 0.9037))
})

##---------------------------------------------------------------
##                  2. Test for summary table                  --
##---------------------------------------------------------------
test_that("Create plan - summary table match", {
  options <- jaspTools::analysisOptions("CreateAttributePlan")
  options$aql <- 0.02
  options$rql <- 0.20
  options$prod_risk <- 0.09
  options$cons_risk <- 0.15
  options$pd_lower <- 0.05
  options$pd_upper <- 0.35
  options$pd_step <- 0.01
  options$showSummary <- TRUE
  
  # 2.1 Binomial
  options$distribution <- "binom"
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  summaryTable <- results[["results"]][["createContainer"]][["collection"]][["createContainer_summaryTable"]][["data"]]
  jaspTools::expect_equal_tables(summaryTable, list(
    0.02, 0.9601, 0.05, 0.8108, 0.06, 0.7511, 0.07, 0.6902, 0.08, 0.6299, 0.09, 0.5711, 0.1, 0.5147, 0.11, 0.4614, 0.12,
    0.4115, 0.13, 0.3653, 0.14, 0.3227, 0.15, 0.2839, 0.16, 0.2487, 0.17, 0.217, 0.18, 0.1885, 0.19, 0.1632, 0.2, 0.1407,
    0.21, 0.1209, 0.22, 0.1035, 0.23, 0.0883, 0.24, 0.075, 0.25, 0.0635, 0.26, 0.0535, 0.27, 0.045, 0.28, 0.0377, 0.29,
    0.0314, 0.3, 0.0261, 0.31, 0.0216, 0.32, 0.0178, 0.33, 0.0146, 0.34, 0.012, 0.35, 0.0098))
  
  # 2.2 Hypergeometric
  options$distribution <- "hypergeom"
  options$lotSize <- 800
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  summaryTable <- results[["results"]][["createContainer"]][["collection"]][["createContainer_summaryTable"]][["data"]]
  jaspTools::expect_equal_tables(summaryTable, list(
    0.02, 0.9618, 0.05, 0.8117, 0.06, 0.7514, 0.07, 0.6901, 0.08, 0.6291, 0.09, 0.5698, 0.1, 0.513, 0.11, 0.4593, 0.12,
    0.4091, 0.13, 0.3626, 0.14, 0.3199, 0.15, 0.281, 0.16, 0.2457, 0.17, 0.214, 0.18, 0.1857, 0.19, 0.1604, 0.2, 0.1381,
    0.21, 0.1184, 0.22, 0.1011, 0.23, 0.0861, 0.24, 0.073, 0.25, 0.0616, 0.26, 0.0519, 0.27, 0.0435, 0.28, 0.0363, 0.29,
    0.0302, 0.3, 0.025, 0.31, 0.0207, 0.32, 0.017, 0.33, 0.0139, 0.34, 0.0114, 0.35, 0.0092))

  # 2.3 Poisson
  options$distribution <- "poisson"
  options$pd_step <- 0.03
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  summaryTable <- results[["results"]][["createContainer"]][["collection"]][["createContainer_summaryTable"]][["data"]]
  jaspTools::expect_equal_tables(summaryTable, list(
    0.02, 0.9538, 0.05, 0.7907, 0.08, 0.6057, 0.11, 0.4423, 0.14, 0.3128, 0.17, 0.2162, 0.2, 0.1468, 0.23, 0.0984, 0.26,
    0.0652, 0.29, 0.0429, 0.32, 0.0279, 0.35, 0.0181))
})

##----------------------------------------------------------------
##                     3. Test for OC Curve                     --
##----------------------------------------------------------------
test_that("Create plan - OC Curve match", {
  options <- jaspTools::analysisOptions("CreateAttributePlan")
  options$aql <- 0.05
  options$rql <- 0.65
  options$prod_risk <- 0.15
  options$cons_risk <- 0.20
  options$pd_lower <- 0.15
  options$pd_upper <- 0.72
  options$showOCCurve <- TRUE
  
  options$showSummary <- FALSE
  options$showAOQCurve <- FALSE
  options$showATICurve <- FALSE

  # 3.1 Binomial
  options$distribution <- "binom" 
  options$pd_step <- 0.02
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["createContainer"]][["collection"]][["createContainer_ocCurve"]][["data"]]
  testPlotBinom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(testPlotBinom, "oc-operating-characteristics-curve-binom")
  
  # 3.2 Hypergeometric
  options$distribution <- "hypergeom"
  options$lotSize <- 2000
  options$pd_step <- 0.001
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["createContainer"]][["collection"]][["createContainer_ocCurve"]][["data"]]
  testPlotHypergeom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(testPlotHypergeom, "oc-operating-characteristics-curve-hypergeom")

  # 3.3 Poisson
  options$distribution <- "poisson"
  options$pd_step <- 0.05
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["createContainer"]][["collection"]][["createContainer_ocCurve"]][["data"]]
  testPlotPoisson <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(testPlotPoisson, "oc-operating-characteristics-curve-poisson")
})

##---------------------------------------------------------------
##                    4. Test for AOQ Curve                    --
##---------------------------------------------------------------
test_that("Create attribute plan - AOQ Curve match", {
  options <- jaspTools::analysisOptions("CreateAttributePlan")
  options$aql <- 0.20
  options$rql <- 0.40
  options$prod_risk <- 0.25
  options$cons_risk <- 0.45
  options$pd_lower <- 0.1
  options$pd_upper <- 0.9
  options$showAOQCurve <- TRUE
  
  options$showSummary <- FALSE
  options$showOCCurve <- FALSE
  options$showATICurve <- FALSE
  
  # 4.1 Binomial
  options$distribution <- "binom"
  options$lotSize <- 1000
  options$pd_step <- 0.1
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["createContainer"]][["collection"]][["createContainer_aoqCurve"]][["data"]]
  aoqPlotBinom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(aoqPlotBinom, "aoq-curve--binom")
  
  # 4.2 Hypergeometric
  options$distribution <- "hypergeom"
  options$lotSize <- 500
  options$sampleSize <- 100
  options$pd_step <- 0.05
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["createContainer"]][["collection"]][["createContainer_aoqCurve"]][["data"]]
  aoqPlotHypergeom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(aoqPlotHypergeom, "aoq-curve--hypergeom")

  # 4.3 Poisson
  options$distribution <- "poisson"
  options$lotSize <- 400
  options$sampleSize <- 50
  options$pd_step <- 0.01
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["createContainer"]][["collection"]][["createContainer_aoqCurve"]][["data"]]
  aoqPlotPoisson <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(aoqPlotPoisson, "aoq-curve--poisson")
})

##---------------------------------------------------------------
##                    5. Test for ATI Curve                    --
##---------------------------------------------------------------
test_that("Create attribute plan - ATI Curve match", {
  options <- jaspTools::analysisOptions("CreateAttributePlan")
  options$aql <- 0.08
  options$rql <- 0.65
  options$prod_risk <- 0.18
  options$cons_risk <- 0.38
  options$pd_lower <- 0.04
  options$pd_upper <- 0.78
  
  options$showATICurve <- TRUE
  
  options$showSummary <- FALSE
  options$showOCCurve <- FALSE
  options$showAOQCurve <- FALSE
  
  # 5.1 Binomial
  options$distribution <- "binom"
  options$lotSize <- 750
  options$pd_step <- 0.2
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["createContainer"]][["collection"]][["createContainer_atiCurve"]][["data"]]
  atiPlotBinom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotBinom, "ati-curve--binom")
  
  # 5.2 Hypergeometric
  options$distribution <- "hypergeom"
  options$lotSize <- 600
  options$pd_step <- 0.1
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["createContainer"]][["collection"]][["createContainer_atiCurve"]][["data"]]
  atiPlotHypergeom <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotHypergeom, "ati-curve--hypergeom")

  # 5.3 Poisson
  options$distribution <- "poisson"
  options$lotSize <- 300
  options$pd_step <- 0.05
  results <- jaspTools::runAnalysis("CreateAttributePlan", "test.csv", options)
  plotName <- results[["results"]][["createContainer"]][["collection"]][["createContainer_atiCurve"]][["data"]]
  atiPlotPoisson <- results[["state"]][["figures"]][[plotName]][["obj"]]
  jaspTools::expect_equal_plots(atiPlotPoisson, "ati-curve--poisson")
})